Repository sonata-project/SonataMediaBundle, pull requests merged in 2018-04, with the labels that each got.

#1388 SyncThumbsCommand PHPCR, ODM manager fix
  src/Command/SyncThumbsCommand.php
Labels: patch

#1418 Fix tests
  tests/Controller/GalleryAdminControllerTest.php
  tests/Controller/MediaAdminControllerTest.php
Labels: critical, pedantic

#1417 Update dependencies
  composer.json
Labels: pedantic

#1411 Fix widget template for MediaType as a child form type
  src/Resources/views/Form/media_widgets.html.twig
Labels: patch
