Repository sonata-project/SonataMediaBundle, pull requests merged in 2018-05, with the labels that each got.

#1425 Bugfix - galleryHasMedia collection is removed on Gallery update
  src/Admin/GalleryAdmin.php
  src/Controller/Api/GalleryController.php
  src/Model/Gallery.php
  src/Model/GalleryInterface.php
  src/Model/GalleryMediaCollectionInterface.php
  src/PHPCR/BaseGallery.php
Labels: minor

#1430 Fix typo in installation doc
  docs/reference/installation.rst
Labels: docs

#1432 Make providers, metadata, and managers services public
  src/Resources/config/category.xml
  src/Resources/config/doctrine_mongodb.xml
  src/Resources/config/doctrine_orm.xml
  src/Resources/config/doctrine_phpcr.xml
  src/Resources/config/gaufrette.xml
  src/Resources/config/provider.xml
Labels: patch

#1435 Force use existing translation strings for Media and Gallery
  src/Admin/BaseMediaAdmin.php
  src/Admin/GalleryAdmin.php
Labels: patch
