Repository sonata-project/SonataMediaBundle, pull requests merged in 2019-01, with the labels that each got.

#1510 Allow KnpLabs/gaufrette 0.8
  composer.json
Labels: minor

#1518 Remove exception when the media is null
  src/Twig/Extension/MediaExtension.php
Labels: patch

#1522 Alias for providers
  src/Resources/config/provider.xml
Labels: minor

#1526 Removed CoreBundle deprecations
  composer.json
  src/Admin/BaseMediaAdmin.php
  src/Admin/GalleryAdmin.php
  src/Block/FeatureMediaBlockService.php
  src/Block/GalleryBlockService.php
  src/Block/GalleryListBlockService.php
  src/Block/MediaBlockService.php
  src/Document/GalleryManager.php
  src/Document/MediaManager.php
  src/Form/Type/ApiDoctrineMediaType.php
  src/Form/Type/ApiGalleryHasMediaType.php
  src/Form/Type/ApiGalleryType.php
  src/PHPCR/GalleryManager.php
  src/PHPCR/MediaManager.php
  src/Resources/config/validation.xml
  src/Serializer/GallerySerializerHandler.php
  src/Serializer/MediaSerializerHandler.php
  tests/Controller/MediaControllerTest.php
Labels: patch

#1529 Remove references to json type
  composer.json
  docs/reference/installation.rst
Labels: docs

#1530 fixed provider metadata type error
  src/Provider/FileProvider.php
  src/Provider/ImageProvider.php
  src/Provider/VimeoProvider.php
  src/Provider/YouTubeProvider.php
  src/Resources/views/MediaAdmin/select_provider.html.twig
  tests/Provider/FileProviderTest.php
  tests/Provider/ImageProviderTest.php
  tests/Provider/VimeoProviderTest.php
  tests/Provider/YouTubeProviderTest.php
Labels: patch

#1540 Apply new cs rules
  src/Admin/BaseMediaAdmin.php
  src/Block/GalleryBlockService.php
  src/CDN/CloudFront.php
  src/CDN/PantherPortal.php
  src/Command/CleanMediaCommand.php
  src/Command/RemoveThumbsCommand.php
  src/Command/SyncThumbsCommand.php
  src/Command/UpdateCdnStatusCommand.php
  src/Controller/Api/GalleryController.php
  src/DependencyInjection/Compiler/AddProviderCompilerPass.php
  src/DependencyInjection/SonataMediaExtension.php
  src/Document/MediaManager.php
  src/Entity/GalleryManager.php
  src/Entity/MediaManager.php
  src/Extra/Pixlr.php
  src/Metadata/AmazonMetadataBuilder.php
  src/Metadata/ProxyMetadataBuilder.php
  src/Model/Media.php
  src/PHPCR/MediaManager.php
  src/Provider/BaseProvider.php
  src/Provider/FileProvider.php
  src/Provider/ImageProvider.php
  src/Provider/YouTubeProvider.php
  src/Resizer/SimpleResizer.php
  src/Resizer/SquareResizer.php
  src/Thumbnail/FormatThumbnail.php
  tests/Command/CleanMediaCommandTest.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/SonataMediaExtensionTest.php
  tests/Filesystem/LocalTest.php
  tests/Provider/DailyMotionProviderTest.php
  tests/Provider/FakeHttpWrapper.php
  tests/Provider/VimeoProviderTest.php
  tests/Provider/YouTubeProviderTest.php
  tests/Security/RolesDownloadStrategyTest.php
Labels: critical, pedantic
