Repository sonata-project/SonataMediaBundle, pull requests merged in 2019-09, with the labels that each got.

#1617 Fix some CS issues in Twig syntax
  src/Resources/views/Block/block_feature_media.html.twig
  src/Resources/views/Extra/pixlr_editor.html.twig
  src/Resources/views/Media/view.html.twig
  src/Resources/views/MediaAdmin/edit.html.twig
  src/Resources/views/MediaAdmin/list_image.html.twig
  src/Resources/views/Provider/thumbnail.html.twig
  src/Resources/views/Provider/view_youtube.html.twig
Labels: pedantic

#1618 Use Twig namespaced classes where possible
  src/Twig/Extension/FormatterMediaExtension.php
  src/Twig/Extension/MediaExtension.php
  src/Twig/Node/MediaNode.php
  src/Twig/Node/PathNode.php
  src/Twig/Node/ThumbnailNode.php
  src/Twig/TokenParser/MediaTokenParser.php
  src/Twig/TokenParser/PathTokenParser.php
  src/Twig/TokenParser/ThumbnailTokenParser.php
  tests/Controller/GalleryAdminControllerTest.php
  tests/Controller/MediaAdminControllerTest.php
  tests/Twig/Extension/MediaExtensionTest.php
Labels: patch

#1620 Remove some non required function calls
  src/Command/AddMassMediaCommand.php
  src/Twig/Extension/MediaExtension.php
Labels: pedantic

#1616 Respect inherited "field_description.options.route.name" value at `list_image.html.twig`
  src/Resources/views/MediaAdmin/list_image.html.twig
Labels: patch

#1627 Add missing translation for admin menu
  src/Resources/translations/SonataAdminBundle.de.xlf
  src/Resources/translations/SonataAdminBundle.en.xlf
Labels: patch

#1628 Add breadcrumb context to seo blocks
  src/Resources/config/seo_block.xml
Labels: minor

#1619 Use Twig namespaced classes
  src/Twig/Extension/MediaExtension.php
  src/Twig/Node/MediaNode.php
  src/Twig/Node/PathNode.php
  src/Twig/Node/ThumbnailNode.php
  src/Twig/TokenParser/MediaTokenParser.php
  src/Twig/TokenParser/PathTokenParser.php
  src/Twig/TokenParser/ThumbnailTokenParser.php
Labels: major

#1608 Fix alt attribute not displaying the media's description in picture elements
  src/Provider/ImageProvider.php
Labels: minor
