Repository sonata-project/SonataMediaBundle, pull requests merged in 2020-03, with the labels that each got.

#1714 Allow "symfony/mime:^5.0"
  composer.json
Labels: minor, vendor

#1717 Allow Twig 3
  composer.json
Labels: minor, vendor

#1719 Clean up tests
  tests/App/config.yml
  tests/Command/CleanMediaCommandTest.php
  tests/Command/FixMediaContextCommandTest.php
  tests/Command/RemoveThumbsCommandTest.php
  tests/Controller/GalleryAdminControllerTest.php
  tests/Controller/MediaAdminControllerTest.php
  tests/Controller/MediaControllerTest.php
  tests/Fixtures/FilesystemTestCase.php
  tests/Functional/Api/MediaControllerTest.php
  tests/Listener/ORM/MediaEventSubscriberTest.php
  tests/Metadata/ProxyMetadataBuilderTest.php
Labels: pedantic

#1724 Document the type of `$mediaManager` in the code snippets
  docs/reference/usage.rst
Labels: docs

#1728 Fix command media:clean-uploads
  src/Command/CleanMediaCommand.php
  src/Resources/config/command.xml
  tests/Command/CleanMediaCommandTest.php
Labels: patch
