Repository sonata-project/SonataMediaBundle, pull requests merged in 2020-02, with the labels that each got.

#1679 Console commands returning status code for Symfony4.4 and 5.0
  src/Command/AddMassMediaCommand.php
  src/Command/AddMediaCommand.php
  src/Command/CleanMediaCommand.php
  src/Command/FixMediaContextCommand.php
  src/Command/MigrateToJsonTypeCommand.php
  src/Command/RefreshMetadataCommand.php
  src/Command/RemoveThumbsCommand.php
  src/Command/SyncThumbsCommand.php
  src/Command/UpdateCdnStatusCommand.php
Labels: patch

#1682 [BC break] Fix commands return type
  src/Command/AddMassMediaCommand.php
  src/Command/AddMediaCommand.php
  src/Command/CleanMediaCommand.php
  src/Command/FixMediaContextCommand.php
  src/Command/MigrateToJsonTypeCommand.php
  src/Command/RefreshMetadataCommand.php
  src/Command/RemoveThumbsCommand.php
  src/Command/SyncThumbsCommand.php
  src/Command/UpdateCdnStatusCommand.php
Labels: major

#1683 Generate path when using VO as UUID representation
  src/Generator/ODMGenerator.php
  tests/Generator/ODMGeneratorTest.php
Labels: patch

#1654 Public (API) controller services for FOSRest
  composer.json
  src/Resources/config/api_controllers.xml
  tests/App/AppKernel.php
  tests/App/Entity/Media.php
  tests/App/config.yml
  tests/App/routes.yml
  tests/App/security.yml
  tests/App/templates/.gitkeep
  tests/Functional/Api/MediaControllerTest.php
Labels: patch

#1675 Made width setting non-mandatory
  src/Resizer/SimpleResizer.php
  tests/Resizer/SimpleResizerTest.php
Labels: minor

#1696 Drop support for Symfony < 4.3
  composer.json
  src/DependencyInjection/Configuration.php
Labels: minor

#1699 Address block bundle deprecations
  composer.json
  src/Block/GalleryBlockService.php
  src/Block/GalleryListBlockService.php
  src/Block/MediaBlockService.php
  src/Resources/config/block.xml
  tests/Block/FeatureMediaBlockServiceTest.php
  tests/Block/GalleryBlockServiceTest.php
  tests/Block/GalleryListBlockServiceTest.php
  tests/Block/MediaBlockServiceTest.php
Labels: minor
