Repository sonata-project/SonataMediaBundle, pull requests merged in 2020-09, with the labels that each got.

#1810 Leverage `Collection::exists()` from `Gallery::getGalleryHasMedias()`
  src/Controller/Api/GalleryController.php
  tests/Controller/Api/GalleryControllerTest.php
Labels: pedantic

#1812 Use "spaceship" operator
  src/Model/Gallery.php
Labels: pedantic

#1814 Fix support for "aws/aws-sdk-php:^3.0"
  UPGRADE-3.x.md
  composer.json
  docs/reference/advanced_configuration.rst
  docs/reference/amazon_s3.rst
  src/CDN/CloudFront.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataMediaExtension.php
  src/Resources/config/gaufrette.xml
  src/Resources/config/media.xml
  tests/App/config.yml
  tests/CDN/CloudFrontTest.php
  tests/DependencyInjection/SonataMediaExtensionTest.php
  tests/Metadata/AmazonMetadataBuilderTest.php
  tests/Metadata/ProxyMetadataBuilderTest.php
Labels: minor

#1818 Drop support for doctrine/mongodb-odm <2.0
  composer.json
Labels: minor

#1826 Small pedantic changes
  src/Provider/DailyMotionProvider.php
  src/Provider/VimeoProvider.php
  src/Provider/YouTubeProvider.php
Labels: pedantic

#1716 Fix mongodb invalid xml mapping Error
  src/Resources/config/doctrine/BaseGallery.mongodb.xml
  src/Resources/config/doctrine/BaseMedia.mongodb.xml
Labels: patch, pending author
