Repository sonata-project/SonataMediaBundle, pull requests merged in 2020-06, with the labels that each got.

#1743 Add image size validation
  docs/reference/media_context.rst
  src/Provider/ImageProvider.php
  src/Resources/config/validation.xml
  src/Resources/config/validators.xml
  src/Resources/translations/SonataMediaBundle.de.xliff
  src/Resources/translations/SonataMediaBundle.en.xliff
  src/Validator/Constraints/ImageUploadDimension.php
  src/Validator/Constraints/ImageUploadDimensionValidator.php
  tests/Fixtures/SonataClassificationBundle/Validator/Constraints/ImageUploadDimensionTest.php
  tests/Fixtures/SonataClassificationBundle/Validator/Constraints/ImageUploadDimensionValidatorTest.php
Labels: minor

#1750 Document the media-orm-pack and media-odm-pack flex recipes
  docs/reference/installation.rst
Labels: docs

#1740 Fix #1731
  src/Block/GalleryBlockService.php
  src/Block/GalleryListBlockService.php
  src/Block/MediaBlockService.php
Labels: patch

#1722 NoDriver should extend ManagerInterface to be able to be passed to `sonata.media.block.gallery_list` service
  src/Model/NoDriverManager.php
  tests/Model/NoDriverManagerTest.php
Labels: patch

#1671 Add max file size as a parameter in the validation message
  src/Provider/FileProvider.php
Labels: minor

#1756 Replace truncate filter with u filter
  composer.json
  docs/reference/installation.rst
  src/DependencyInjection/SonataMediaExtension.php
  src/Resources/views/MediaAdmin/list_outer_rows_mosaic.html.twig
  tests/DependencyInjection/SonataMediaExtensionTest.php
Labels: patch

#1757 Add missing interface to NoDriverManager
  src/Model/NoDriverManager.php
Labels: patch

#1758 Fix StringExtension registration
  src/DependencyInjection/Compiler/TwigStringExtensionCompilerPass.php
  src/DependencyInjection/SonataMediaExtension.php
  src/SonataMediaBundle.php
  tests/DependencyInjection/Compiler/AddProviderCompilerPassTest.php
  tests/DependencyInjection/Compiler/ThumbnailCompilerPassTest.php
  tests/DependencyInjection/Compiler/TwigStringExtensionCompilerPassTest.php
  tests/DependencyInjection/SonataMediaExtensionTest.php
Labels: patch
