Repository sonata-project/SonataMediaBundle, pull requests merged in 2020-08, with the labels that each got.

#1777 Rename GalleryItems
  docs/reference/installation.rst
  src/Admin/GalleryAdmin.php
  src/Controller/Api/GalleryController.php
  src/Model/Gallery.php
  src/Model/GalleryInterface.php
  src/Resources/translations/SonataMediaBundle.ca.xliff
  src/Resources/translations/SonataMediaBundle.cs.xliff
Labels: pedantic

#1748 Update custom service provider configuration documentation
  docs/reference/creating_a_provider_class.rst
Labels: docs, pedantic

#1774 endpoint configuration for s3 storage
  docs/reference/amazon_s3.rst
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataMediaExtension.php
  tests/DependencyInjection/SonataMediaExtensionTest.php
Labels: minor

#1786 Allow some symfony/* dependencies to use version ^5.1
  composer.json
Labels: minor
