Repository sonata-project/SonataMediaBundle, pull requests merged in 2021-03, with the labels that each got.

#1934 Replace some `\RuntimeException` exceptions with `\BadMethodCallException`
  src/Document/GalleryManager.php
  src/Document/MediaManager.php
  src/PHPCR/GalleryManager.php
  src/PHPCR/MediaManager.php
Labels: major

#1940 Add CropResizer
  docs/reference/advanced_configuration.rst
  docs/reference/installation.rst
  src/DependencyInjection/SonataMediaExtension.php
  src/Resizer/CropResizer.php
  src/Resizer/ResizerInterface.php
  src/Resources/config/media.xml
  tests/Resizer/CropResizerTest.php
Labels: Needs: Documentation, feature

#1906 allow PHP 8.0
  .github/workflows/test.yaml
  composer.json
Labels: minor

#1930 Update constraints in order to allow some "symfony/*:^5.2" deps
  composer.json
  tests/Controller/MediaAdminControllerTest.php
Labels: dependencies, minor

#1939 Narrow some constructor types for `RolesDownloadStrategy` and `SessionDownloadStrategy`
  src/Security/RolesDownloadStrategy.php
  src/Security/SessionDownloadStrategy.php
  tests/Security/SessionDownloadStrategyTest.php
Labels: minor

#1943 Declare conflict against nelmio/api-doc-bundle <2.13.5 || >=4.0
  composer.json
Labels: minor

#1923 Add translation contracts
  UPGRADE-3.x.md
  composer.json
  src/Security/ForbiddenDownloadStrategy.php
  src/Security/PublicDownloadStrategy.php
  src/Security/RolesDownloadStrategy.php
  src/Security/SessionDownloadStrategy.php
  tests/Security/ForbiddenDownloadStrategyTest.php
  tests/Security/PublicDownloadStrategyTest.php
  tests/Security/RolesDownloadStrategyTest.php
  tests/Security/SessionDownloadStrategyTest.php
Labels: minor

#1938 Remove buzz
  UPGRADE-4.0.md
  composer.json
  docs/reference/advanced_configuration.rst
  src/Client/BuzzClient.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataMediaExtension.php
  src/Provider/BaseVideoProvider.php
  src/Provider/DailyMotionProvider.php
  src/Provider/VimeoProvider.php
  src/Provider/YouTubeProvider.php
  src/Resources/config/http_client.xml
  src/Resources/config/provider.xml
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/SonataMediaExtensionTest.php
  tests/Provider/DailyMotionProviderTest.php
  tests/Provider/VimeoProviderTest.php
  tests/Provider/YouTubeProviderTest.php
Labels: minor
