Repository sonata-project/SonataMediaBundle, pull requests merged in 2021-06, with the labels that each got.

#1963 Upgrade Sonata to v4
  .github/workflows/test.yaml
  composer.json
  src/Admin/BaseMediaAdmin.php
  src/Admin/GalleryAdmin.php
  src/Admin/GalleryItemAdmin.php
  src/Admin/ODM/MediaAdmin.php
  src/Admin/ORM/MediaAdmin.php
  src/Admin/PHPCR/GalleryAdmin.php
  src/Admin/PHPCR/MediaAdmin.php
  src/Block/Breadcrumb/BaseGalleryBreadcrumbBlockService.php
  src/Block/Breadcrumb/GalleryIndexBreadcrumbBlockService.php
  src/Block/Breadcrumb/GalleryViewBreadcrumbBlockService.php
  src/Block/Breadcrumb/MediaViewBreadcrumbBlockService.php
  src/Block/FeatureMediaBlockService.php
  src/Block/GalleryBlockService.php
  src/Block/GalleryListBlockService.php
  src/Block/MediaBlockService.php
  src/Controller/Api/MediaController.php
  src/Controller/GalleryAdminController.php
  src/Controller/MediaAdminController.php
  src/Extra/Pixlr.php
  src/Provider/BaseVideoProvider.php
  src/Provider/FileProvider.php
  src/Provider/MediaProviderInterface.php
  src/Resources/config/block.xml
  src/Resources/config/extra.xml
  src/Resources/config/seo_block.xml
  src/Templating/Helper/MediaHelper.php
  tests/Admin/BaseMediaAdminTest.php
  tests/Block/Breadcrumb/BreadcrumbGalleryBlockService_Test.php
  tests/Block/Breadcrumb/BreadcrumbTest.php
  tests/Block/FeatureMediaBlockServiceTest.php
  tests/Block/GalleryBlockServiceTest.php
  tests/Block/GalleryListBlockServiceTest.php
  tests/Block/MediaBlockServiceTest.php
  tests/Controller/GalleryAdminControllerTest.php
  tests/Controller/MediaAdminControllerTest.php
  tests/Provider/AbstractProviderTest.php
  tests/Provider/BaseProviderTest.php
  tests/Provider/DailyMotionProviderTest.php
  tests/Provider/FileProviderTest.php
  tests/Provider/VimeoProviderTest.php
  tests/Provider/YouTubeProviderTest.php
Labels: major

#1871 Update MediaManager.php
  src/Document/MediaManager.php
Labels: Needs: Tests, patch

#1967 Add phpstan and psalm
  .github/workflows/qa.yaml
  composer.json
  phpstan-baseline.neon
  phpstan.neon.dist
  psalm-baseline.xml
  psalm.xml
  src/Admin/BaseMediaAdmin.php
  src/Admin/GalleryAdmin.php
  src/Admin/GalleryHasMediaAdmin.php
  src/Admin/ODM/MediaAdmin.php
  src/Admin/ORM/MediaAdmin.php
  src/Admin/PHPCR/GalleryAdmin.php
  src/Admin/PHPCR/MediaAdmin.php
  src/Block/FeatureMediaBlockService.php
  src/Block/GalleryBlockService.php
  src/Block/GalleryListBlockService.php
  src/Block/MediaBlockService.php
  src/DependencyInjection/Configuration.php
  src/Entity/MediaManager.php
  src/Filesystem/Replicate.php
  src/Form/DataTransformer/ProviderDataTransformer.php
  src/Form/DataTransformer/ServiceProviderDataTransformer.php
  src/Model/Media.php
  src/Provider/BaseVideoProvider.php
  src/Provider/FileProvider.php
  src/Provider/MediaProviderInterface.php
  src/Templating/Helper/MediaHelper.php
  tests/App/AppKernel.php
  tests/CDN/CloudFrontTest.php
  tests/Controller/Api/GalleryControllerTest.php
  tests/Document/MediaManagerTest.php
  tests/Fixtures/SonataClassificationBundle/Model/CategoryManagerInterface.php
  tests/PHPCR/MediaManagerTest.php
  tests/Provider/AbstractProviderTest.php
  tests/Provider/DailyMotionProviderTest.php
  tests/Provider/FileProviderTest.php
  tests/Provider/VimeoProviderTest.php
  tests/Provider/YouTubeProviderTest.php
Labels: pedantic

#1977 Remove old nelmio version
  UPGRADE-4.0.md
  composer.json
  src/Controller/Api/Legacy/GalleryController.php
  src/Controller/Api/Legacy/MediaController.php
  src/DependencyInjection/SonataMediaExtension.php
  src/Resources/config/api_controllers_legacy.php
  src/Resources/config/routing/api.xml
  src/Resources/config/routing/api/gallery.xml
  src/Resources/config/routing/api/media.xml
  tests/App/AppKernel.php
  tests/App/Resources/config/routing/api_nelmio_v2.yml
Labels: major

#1973 Compatibility with Symfony 5 and Twig 3
  composer.json
  docs/reference/advanced_configuration.rst
  docs/reference/installation.rst
  docs/reference/troubleshooting.rst
  src/Controller/Api/GalleryController.php
  src/Controller/GalleryAdminController.php
  src/Controller/MediaAdminController.php
  src/DependencyInjection/Configuration.php
  src/Resources/config/api_controllers.php
  src/Resources/config/routing/gallery.xml
  src/Resources/config/routing/media.xml
  src/Resources/config/routing/pixlr.xml
  src/Resources/views/GalleryAdmin/list.html.twig
  src/Twig/Extension/MediaExtension.php
  tests/App/AppKernel.php
  tests/App/Resources/config/config.yml
  tests/App/Resources/config/config_symfony_v5.yml
  tests/App/Resources/config/routing/routes.yml
  tests/App/Resources/config/security.yml
  tests/App/Resources/config/services.php
  tests/App/Resources/views/truncate_test.html.twig
  tests/Controller/Api/GalleryControllerTest.php
  tests/Twig/Extension/MediaExtensionTest.php
Labels: major

#1983 Improve SonataMedia Adapters
  phpstan-baseline.neon
  phpstan.neon.dist
  psalm-baseline.xml
  psalm.xml
  src/DependencyInjection/SonataMediaExtension.php
  src/Resources/config/gaufrette.php
Labels: major

#1979 Avoid defining services on the Extension class
  UPGRADE-4.0.md
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataMediaExtension.php
  src/Resizer/ImagineCompatibleResizerTrait.php
  src/Resizer/SimpleResizer.php
  src/Resizer/SquareResizer.php
  src/Resources/config/media.php
  tests/Resizer/ImagineCompatibleResizerTraitTest.php
  tests/Resizer/SimpleResizerTest.php
  tests/Resizer/SquareResizerTest.php
Labels: major

#1989 Test integration with classification-bundle
  UPGRADE-4.0.md
  composer.json
  docs/reference/advanced_configuration.rst
  src/Admin/BaseMediaAdmin.php
  src/Command/FixMediaContextCommand.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataMediaExtension.php
  src/Listener/ORM/MediaEventSubscriber.php
  src/Model/CategoryManager.php
  src/Model/CategoryManagerInterface.php
  src/Resources/config/category.php
  tests/Admin/BaseMediaAdminTest.php
  tests/Admin/ORM/MediaAdminTest.php
  tests/Command/FixMediaContextCommandTest.php
  tests/Controller/MediaAdminControllerTest.php
  tests/DependencyInjection/SonataMediaExtensionTest.php
  tests/Fixtures/SonataClassificationBundle/Entity/BaseCategory.php
  tests/Fixtures/SonataClassificationBundle/Entity/BaseContext.php
  tests/Fixtures/SonataClassificationBundle/Model/Category.php
  tests/Fixtures/SonataClassificationBundle/Model/CategoryInterface.php
  tests/Fixtures/SonataClassificationBundle/Model/CategoryManagerInterface.php
  tests/Fixtures/SonataClassificationBundle/Model/Context.php
  tests/Fixtures/SonataClassificationBundle/Model/ContextInterface.php
  tests/Fixtures/SonataClassificationBundle/Model/ContextManagerInterface.php
  tests/Listener/ORM/MediaEventSubscriberTest.php
  tests/Validator/Constraints/ImageUploadDimensionTest.php
  tests/Validator/Constraints/ImageUploadDimensionValidatorTest.php
Labels: major

#1991 Fix event listeners
  src/Listener/BaseMediaEventSubscriber.php
  src/Listener/ODM/MediaEventSubscriber.php
  src/Listener/ORM/MediaEventSubscriber.php
  tests/Listener/ORM/MediaEventSubscriberTest.php
Labels: pedantic

#1992 Add typehints to Entities
  src/Document/BaseGallery.php
  src/Document/BaseMedia.php
  src/Entity/BaseGallery.php
  src/Entity/BaseMedia.php
  src/Model/Gallery.php
  src/Model/GalleryInterface.php
  src/Model/GalleryItem.php
  src/Model/GalleryItemInterface.php
  src/Model/Media.php
  src/Model/MediaInterface.php
  src/Provider/VimeoProvider.php
  tests/App/Entity/Category.php
  tests/App/Entity/Context.php
  tests/App/Entity/Gallery.php
  tests/App/Entity/GalleryItem.php
  tests/App/Entity/Media.php
  tests/Block/GalleryBlockServiceTest.php
  tests/Controller/Api/GalleryControllerTest.php
  tests/Entity/MediaTest.php
Labels: major

#1995 Move datagrid-bundle to require section
  composer.json
Labels: pedantic

#1997 Add typehints to tests
  tests/Admin/BaseMediaAdminTest.php
  tests/Admin/GalleryAdminTest.php
  tests/Admin/GalleryItemAdminTest.php
  tests/Admin/ORM/MediaAdminTest.php
  tests/App/Provider/TestProvider.php
  tests/Block/FeatureMediaBlockServiceTest.php
  tests/Block/GalleryListBlockServiceTest.php
  tests/Command/CleanMediaCommandTest.php
  tests/Command/FixMediaContextCommandTest.php
  tests/Command/RemoveThumbsCommandTest.php
  tests/Controller/Api/GalleryTest.php
  tests/Controller/GalleryAdminControllerTest.php
  tests/Document/Media.php
  tests/Document/MediaManagerTest.php
  tests/Entity/Media.php
  tests/Fixtures/FilesystemTestCase.php
  tests/Form/Type/AbstractTypeTest.php
  tests/Model/MediaTest.php
  tests/Model/NoDriverManagerTest.php
  tests/Provider/AbstractProviderTest.php
  tests/Provider/FakeHttpWrapper.php
Labels: pedantic

#1996 Add typehints
  src/Admin/BaseMediaAdmin.php
  src/Admin/GalleryAdmin.php
  src/Block/FeatureMediaBlockService.php
  src/CDN/CDNInterface.php
  src/CDN/CloudFrontVersion3.php
  src/CDN/Fallback.php
  src/CDN/PantherPortal.php
  src/CDN/Server.php
  src/Command/AddMassMediaCommand.php
  src/Command/CleanMediaCommand.php
  src/Command/RefreshMetadataCommand.php
  src/Command/RemoveThumbsCommand.php
  src/Command/SyncThumbsCommand.php
  src/Command/UpdateCdnStatusCommand.php
  src/Consumer/CreateThumbnailConsumer.php
  tests/CDN/PantherPortalTest.php
Labels: major

#1998 Typehints to controllers
  src/Controller/Api/GalleryController.php
  src/Controller/Api/MediaController.php
  src/Controller/MediaController.php
Labels: major

#1990 Reduce visibility
  src/Admin/BaseMediaAdmin.php
  src/Admin/GalleryAdmin.php
  src/Admin/GalleryItemAdmin.php
  src/Block/GalleryListBlockService.php
  src/Command/AddMassMediaCommand.php
  src/Command/AddMediaCommand.php
  src/Command/CleanMediaCommand.php
  src/Command/FixMediaContextCommand.php
  src/Command/MigrateToJsonTypeCommand.php
  src/Command/RefreshMetadataCommand.php
  src/Command/RemoveThumbsCommand.php
  src/Command/SyncThumbsCommand.php
  src/Command/UpdateCdnStatusCommand.php
  src/Extra/ApiMediaFile.php
  src/Form/Type/ApiMediaType.php
  src/Form/Type/MediaType.php
  src/Listener/ORM/MediaEventSubscriber.php
  src/Provider/DailyMotionProvider.php
  src/Provider/ImageProvider.php
  src/Provider/MediaProviderInterface.php
  src/Provider/Pool.php
  src/Provider/YouTubeProvider.php
  src/Twig/Extension/FormatterMediaExtension.php
  src/Twig/Extension/MediaExtension.php
  src/Twig/Node/MediaNode.php
  src/Twig/Node/PathNode.php
  src/Twig/Node/ThumbnailNode.php
  src/Twig/TokenParser/MediaTokenParser.php
  src/Twig/TokenParser/PathTokenParser.php
  src/Twig/TokenParser/ThumbnailTokenParser.php
  src/Validator/FormatValidator.php
  tests/Admin/GalleryAdminTest.php
  tests/Block/GalleryListBlockServiceTest.php
  tests/Command/CleanMediaCommandTest.php
  tests/Command/FixMediaContextCommandTest.php
  tests/Controller/Api/MediaControllerTest.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/Document/MediaManagerTest.php
  tests/Entity/GalleryManagerTest.php
  tests/Entity/MediaManagerTest.php
  tests/Provider/PoolTest.php
Labels: major

#2000 Fix build
  src/Admin/BaseMediaAdmin.php
  src/Command/FixMediaContextCommand.php
  src/Controller/MediaAdminController.php
  src/Resources/config/category.php
  src/Resources/config/commands.php
  src/Resources/config/doctrine_mongodb_admin.php
  src/Resources/config/doctrine_orm_admin.php
  tests/Admin/BaseMediaAdminTest.php
  tests/Command/FixMediaContextCommandTest.php
  tests/Controller/MediaAdminControllerTest.php
Labels: pedantic
