Repository sonata-project/SonataMediaBundle, pull requests merged in 2021-09, with the labels that each got.

#2088 Remove placeholders from translations
  src/Resources/translations/SonataMediaBundle.bg.xliff
  src/Resources/translations/SonataMediaBundle.ca.xliff
  src/Resources/translations/SonataMediaBundle.cs.xliff
  src/Resources/translations/SonataMediaBundle.de.xliff
  src/Resources/translations/SonataMediaBundle.en.xliff
  src/Resources/translations/SonataMediaBundle.es.xliff
  src/Resources/translations/SonataMediaBundle.fa.xliff
  src/Resources/translations/SonataMediaBundle.fi.xliff
  src/Resources/translations/SonataMediaBundle.fr.xliff
  src/Resources/translations/SonataMediaBundle.hu.xliff
  src/Resources/translations/SonataMediaBundle.ja.xliff
  src/Resources/translations/SonataMediaBundle.lt.xliff
  src/Resources/translations/SonataMediaBundle.nl.xliff
  src/Resources/translations/SonataMediaBundle.pl.xliff
  src/Resources/translations/SonataMediaBundle.pt_BR.xliff
  src/Resources/translations/SonataMediaBundle.ro.xliff
  src/Resources/translations/SonataMediaBundle.uk.xliff
Labels: patch

#2038 Increase psalm to level 3
  docs/reference/creating_a_provider_class.rst
  psalm.xml
  src/CDN/PantherPortal.php
  src/Command/AddMassMediaCommand.php
  src/Command/CleanMediaCommand.php
  src/Command/RefreshMetadataCommand.php
  src/Command/RemoveThumbsCommand.php
  src/Command/SyncThumbsCommand.php
  src/Command/UpdateCdnStatusCommand.php
  src/Generator/GeneratorInterface.php
  src/Generator/IdGenerator.php
  src/Generator/PathGenerator.php
  src/Generator/UuidGenerator.php
  src/Listener/ORM/MediaEventSubscriber.php
  src/Metadata/ProxyMetadataBuilder.php
  src/Model/Gallery.php
  src/Provider/BaseProvider.php
  src/Provider/BaseVideoProvider.php
  src/Provider/DailyMotionProvider.php
  src/Provider/FileProvider.php
  src/Provider/ImageProvider.php
  src/Provider/MediaProviderInterface.php
  src/Provider/Pool.php
  src/Provider/VimeoProvider.php
  src/Provider/YouTubeProvider.php
  src/Resizer/CropResizer.php
  src/Resizer/SimpleResizer.php
  src/Resizer/SquareResizer.php
  src/Thumbnail/FormatThumbnail.php
  tests/App/Provider/TestProvider.php
  tests/CDN/PantherPortalTest.php
  tests/Provider/BaseProviderTest.php
  tests/Provider/DailyMotionProviderTest.php
  tests/Provider/FileProviderTest.php
  tests/Provider/VimeoProviderTest.php
  tests/Provider/YouTubeProviderTest.php
Labels: major

#2094 Fix admin format
  src/DependencyInjection/Compiler/AddProviderCompilerPass.php
  src/DependencyInjection/Configuration.php
  src/Provider/BaseVideoProvider.php
  src/Provider/MediaProviderInterface.php
  src/Thumbnail/FormatThumbnail.php
  tests/Block/MediaBlockServiceTest.php
  tests/Controller/Api/MediaControllerTest.php
  tests/Controller/MediaControllerTest.php
  tests/DependencyInjection/Compiler/AddProviderCompilerPassTest.php
  tests/Provider/BaseProviderTest.php
  tests/Provider/DailyMotionProviderTest.php
  tests/Provider/FileProviderTest.php
  tests/Provider/ImageProviderTest.php
  tests/Provider/VimeoProviderTest.php
  tests/Provider/YouTubeProviderTest.php
  tests/Resizer/CropResizerTest.php
  tests/Resizer/SimpleResizerTest.php
  tests/Resizer/SquareResizerTest.php
  tests/Thumbnail/FormatThumbnailTest.php
  tests/Validator/FormatValidatorTest.php
Labels: major

#2096 Add missing methods to interfaces and abstract classes
  src/Model/GalleryInterface.php
  src/Model/Media.php
  src/Model/MediaInterface.php
  src/Provider/BaseVideoProvider.php
  src/Provider/MediaProviderInterface.php
  tests/Fixtures/SonataClassificationBundle/Model/CategoryInterface.php
  tests/Fixtures/SonataClassificationBundle/Model/ContextInterface.php
Labels: minor

#2082 Fix some return types
  UPGRADE-3.x.md
  src/Listener/BaseMediaEventSubscriber.php
  src/Listener/ODM/MediaEventSubscriber.php
  src/Listener/ORM/MediaEventSubscriber.php
  src/Listener/PHPCR/MediaEventSubscriber.php
  src/Provider/FileProvider.php
  tests/Listener/ORM/MediaEventSubscriberTest.php
Labels: minor

#2093 Avoid using container on ProxyMetadataBuilder
  src/Metadata/ProxyMetadataBuilder.php
  src/Resources/config/gaufrette.php
  tests/DependencyInjection/SonataMediaExtensionTest.php
  tests/Metadata/ProxyMetadataBuilderTest.php
Labels: major

#2101 Fix upload of media through MediaType
  src/Form/Type/MediaType.php
Labels: patch

#2102 Improve consistency on twig views
  src/Resources/views/Block/block_feature_media.html.twig
  src/Resources/views/Block/block_gallery.html.twig
  src/Resources/views/Block/block_gallery_list.html.twig
  src/Resources/views/Block/block_media.html.twig
  src/Resources/views/Extra/pixlr_editor.html.twig
  src/Resources/views/Extra/pixlr_exit.html.twig
  src/Resources/views/Form/media_widgets.html.twig
  src/Resources/views/Gallery/view.html.twig
  src/Resources/views/GalleryAdmin/list.html.twig
  src/Resources/views/Media/view.html.twig
  src/Resources/views/MediaAdmin/edit.html.twig
  src/Resources/views/MediaAdmin/inner_row_media.html.twig
  src/Resources/views/MediaAdmin/list.html.twig
  src/Resources/views/MediaAdmin/list_image.html.twig
  src/Resources/views/MediaAdmin/list_outer_rows_mosaic.html.twig
  src/Resources/views/MediaAdmin/select_provider.html.twig
  src/Resources/views/Provider/thumbnail.html.twig
  src/Resources/views/Provider/view_image.html.twig
  src/Resources/views/Provider/view_vimeo.html.twig
Labels: pedantic

#2105 Deprecate index and view controller method
  UPGRADE-3.x.md
  src/Block/Breadcrumb/BaseGalleryBreadcrumbBlockService.php
  src/Block/Breadcrumb/GalleryIndexBreadcrumbBlockService.php
  src/Block/Breadcrumb/GalleryViewBreadcrumbBlockService.php
  src/Block/Breadcrumb/MediaViewBreadcrumbBlockService.php
  src/Controller/GalleryController.php
  src/Controller/MediaController.php
  tests/Controller/MediaControllerTest.php
Labels: minor

#2113 Deprecate Pixlr integration
  UPGRADE-3.x.md
  src/DependencyInjection/Configuration.php
  src/Extra/Pixlr.php
  src/Resources/views/Extra/pixlr_editor.html.twig
  src/Resources/views/Extra/pixlr_exit.html.twig
  src/Twig/GlobalVariables.php
Labels: minor

#2114 Fix media route for download action
  src/Resources/config/routing/media.xml
Labels: bug

#2116 Check for each role separately on downloadAction
  src/Security/RolesDownloadStrategy.php
  tests/Security/RolesDownloadStrategyTest.php
Labels: patch

#2121 Fix deprecations from Symfony 5.4 typing system
  src/Controller/GalleryAdminController.php
  src/Controller/MediaAdminController.php
  src/Filesystem/Replicate.php
  src/Form/DataTransformer/ProviderDataTransformer.php
  src/Form/DataTransformer/ServiceProviderDataTransformer.php
  src/Form/Type/ApiMediaType.php
  src/Form/Type/MediaType.php
  src/Listener/ODM/MediaEventSubscriber.php
  src/Listener/ORM/MediaEventSubscriber.php
  src/Twig/TokenParser/MediaTokenParser.php
  src/Twig/TokenParser/PathTokenParser.php
  src/Twig/TokenParser/ThumbnailTokenParser.php
  src/Validator/Constraints/ValidMediaFormat.php
  tests/App/AppKernel.php
  tests/Filesystem/ReplicateTest.php
  tests/Provider/DailyMotionProviderTest.php
  tests/Provider/VimeoProviderTest.php
  tests/Provider/YouTubeProviderTest.php
Labels: major

#2118 [RFC] Deprecate ReST API
  UPGRADE-3.x.md
  src/Controller/Api/GalleryController.php
  src/Controller/Api/MediaController.php
  src/DependencyInjection/SonataMediaExtension.php
  src/Document/GalleryManager.php
  src/Document/MediaManager.php
  src/Entity/GalleryManager.php
  src/Entity/MediaManager.php
  src/Extra/ApiMediaFile.php
  src/Form/Type/ApiDoctrineMediaType.php
  src/Form/Type/ApiGalleryHasMediaType.php
  src/Form/Type/ApiGalleryType.php
  src/Form/Type/ApiMediaType.php
  src/Model/GalleryManagerInterface.php
  src/Model/MediaManagerInterface.php
  src/Serializer/GallerySerializerHandler.php
  src/Serializer/MediaSerializerHandler.php
  tests/Controller/Api/GalleryControllerTest.php
  tests/Controller/Api/MediaControllerTest.php
  tests/Entity/GalleryManagerTest.php
  tests/Entity/MediaManagerTest.php
Labels: minor

#2125 Improve templates
  src/Resources/views/Block/block_feature_media.html.twig
  src/Resources/views/Block/block_gallery.html.twig
  src/Resources/views/Block/block_media.html.twig
  src/Resources/views/GalleryAdmin/list.html.twig
  src/Resources/views/MediaAdmin/edit.html.twig
  src/Resources/views/MediaAdmin/inner_row_media.html.twig
  src/Resources/views/MediaAdmin/list_outer_rows_mosaic.html.twig
  src/Resources/views/Provider/view_dailymotion.html.twig
  src/Resources/views/Provider/view_vimeo.html.twig
  src/Resources/views/Provider/view_youtube.html.twig
Labels: major

#2137 Make FeatureMediaBlockService not extend from MediaBlockService
  src/Block/FeatureMediaBlockService.php
  src/Block/GalleryBlockService.php
  src/Block/MediaBlockService.php
  src/Command/AddMassMediaCommand.php
  src/Command/AddMediaCommand.php
  src/Command/RefreshMetadataCommand.php
  src/Command/RemoveThumbsCommand.php
  src/Command/SyncThumbsCommand.php
  src/Command/UpdateCdnStatusCommand.php
  src/Consumer/CreateThumbnailConsumer.php
  src/Twig/Extension/MediaExtension.php
  tests/Block/FeatureMediaBlockServiceTest.php
  tests/Block/GalleryBlockServiceTest.php
  tests/Block/MediaBlockServiceTest.php
  tests/Twig/Extension/MediaExtensionTest.php
Labels: major

#2131 Add Symfony messenger integration
  composer.json
  docs/index.rst
  docs/reference/advanced_configuration.rst
  docs/reference/messenger.rst
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataMediaExtension.php
  src/Messenger/GenerateThumbnailsHandler.php
  src/Messenger/GenerateThumbnailsMessage.php
  src/Resources/config/messenger.xml
  src/Thumbnail/MessengerThumbnail.php
  tests/App/Entity/Gallery.php
  tests/App/Entity/GalleryHasMedia.php
  tests/App/Entity/Media.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/SonataMediaExtensionTest.php
  tests/Messenger/GenerateThumbnailsHandlerTest.php
  tests/Thumbnail/MessengerThumbnailTest.php
Labels: minor

#2140 Cleanup psalm baseline
  psalm-baseline.xml
Labels: pedantic

#2139 Deprecate SonataNotificationBundle integration
  UPGRADE-3.x.md
  src/Consumer/CreateThumbnailConsumer.php
  src/DependencyInjection/SonataMediaExtension.php
  src/Thumbnail/ConsumerThumbnail.php
  tests/Thumbnail/ConsumerThumbnailTest.php
Labels: minor

#2141 Update homepage
  composer.json
Labels: pedantic

#2138 Implement MediaDownloadAction
  src/Action/MediaDownloadAction.php
  src/Controller/MediaController.php
  src/DependencyInjection/SonataMediaExtension.php
  src/Resources/config/actions.xml
  src/Resources/config/routing/media.xml
  tests/Action/MediaDownloadActionTest.php
  tests/Controller/MediaControllerTest.php
Labels: minor
