Repository sonata-project/SonataMediaBundle, pull requests merged in 2021-10, with the labels that each got.

#2144 Increase Psalm to level 2
  psalm-baseline.xml
  psalm.xml
  src/Command/RefreshMetadataCommand.php
  src/Command/RemoveThumbsCommand.php
  src/Command/SyncThumbsCommand.php
  src/Command/UpdateCdnStatusCommand.php
  src/Filesystem/Replicate.php
  src/Form/DataTransformer/ProviderDataTransformer.php
  src/Form/DataTransformer/ServiceProviderDataTransformer.php
  src/Model/NoDriverGalleryManager.php
  src/Model/NoDriverMediaManager.php
  src/Resizer/SimpleResizer.php
  src/Twig/TokenParser/MediaTokenParser.php
  src/Twig/TokenParser/PathTokenParser.php
  src/Twig/TokenParser/ThumbnailTokenParser.php
  tests/Admin/GalleryAdminTest.php
  tests/Admin/GalleryItemAdminTest.php
  tests/Admin/ORM/MediaAdminTest.php
  tests/App/AppKernel.php
  tests/Command/RemoveThumbsCommandTest.php
  tests/Controller/GalleryAdminControllerTest.php
  tests/Twig/Extension/MediaExtensionTest.php
Labels: major

#2145 Move to twig functions
  UPGRADE-3.x.md
  docs/reference/helpers.rst
  docs/reference/troubleshooting.rst
  src/Resources/config/twig.xml
  src/Resources/views/Block/block_feature_media.html.twig
  src/Resources/views/Block/block_gallery.html.twig
  src/Resources/views/Block/block_media.html.twig
  src/Resources/views/Media/view.html.twig
  src/Resources/views/MediaAdmin/edit.html.twig
  src/Twig/Extension/FormatterMediaExtension.php
  src/Twig/Extension/MediaExtension.php
  src/Twig/MediaRuntime.php
  src/Twig/Node/MediaNode.php
  src/Twig/Node/PathNode.php
  src/Twig/Node/ThumbnailNode.php
  src/Twig/TokenParser/MediaTokenParser.php
  src/Twig/TokenParser/PathTokenParser.php
  src/Twig/TokenParser/ThumbnailTokenParser.php
  tests/Twig/Extension/MediaExtensionTest.php
  tests/Twig/MediaRuntimeTest.php
Labels: minor

#2149 Fix definition of MediaRuntime
  src/Resources/config/twig.xml
  tests/DependencyInjection/SonataMediaExtensionTest.php
Labels: critical, patch

#2146 Added more information for VimeoProvider in service configuration
  docs/reference/creating_a_provider_class.rst
Labels: docs

#2150 Only load controllers if SonataAdminBundle is enabled
  src/DependencyInjection/SonataMediaExtension.php
  tests/DependencyInjection/SonataMediaExtensionTest.php
Labels: patch

#2187 Deprecate PantherPortal
  UPGRADE-3.x.md
  src/CDN/PantherPortal.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataMediaExtension.php
Labels: minor

#2189 Set Cloudfront class on service definition
  src/DependencyInjection/SonataMediaExtension.php
  src/Resources/config/media.php
Labels: pedantic

#2190 Use cloudfront instead of panther in the upgrade example
  UPGRADE-3.x.md
Labels: pedantic
