Repository sonata-project/SonataMediaBundle, pull requests merged in 2021-08, with the labels that each got.

#2016 Increase psalm to level 4
  psalm.xml
  src/Admin/BaseMediaAdmin.php
  src/Admin/GalleryAdmin.php
  src/Block/GalleryBlockService.php
  src/CDN/CloudFrontVersion3.php
  src/Command/UpdateCdnStatusCommand.php
  src/DependencyInjection/Configuration.php
  src/Extra/Pixlr.php
  src/Form/DataTransformer/ProviderDataTransformer.php
  src/Form/Type/ApiMediaType.php
  src/Form/Type/MediaType.php
  src/Metadata/AmazonMetadataBuilder.php
  src/Model/Gallery.php
  src/Model/GalleryInterface.php
  src/Provider/BaseVideoProvider.php
  src/Provider/MediaProviderInterface.php
  src/Provider/Pool.php
  src/Resizer/CropResizer.php
  src/Resizer/ResizerInterface.php
  src/Resizer/SquareResizer.php
  src/Twig/TokenParser/MediaTokenParser.php
  src/Twig/TokenParser/PathTokenParser.php
  src/Twig/TokenParser/ThumbnailTokenParser.php
  tests/Controller/GalleryAdminControllerTest.php
  tests/Controller/MediaAdminControllerTest.php
  tests/Controller/MediaControllerTest.php
  tests/Entity/MediaTest.php
  tests/Form/DataTransformer/ProviderDataTransformerTest.php
  tests/Form/Type/MediaTypeTest.php
  tests/Metadata/AmazonMetadataBuilderTest.php
  tests/Model/NoDriverGalleryManagerTest.php
  tests/Model/NoDriverMediaManagerTest.php
  tests/Provider/AbstractProviderTest.php
  tests/Provider/DailyMotionProviderTest.php
  tests/Provider/FileProviderTest.php
  tests/Provider/ImageProviderTest.php
  tests/Provider/VimeoProviderTest.php
  tests/Provider/YouTubeProviderTest.php
  tests/Resizer/SimpleResizerTest.php
  tests/Resizer/SquareResizerTest.php
  tests/Twig/Extension/MediaExtensionTest.php
  tests/Validator/Constraints/ImageUploadDimensionValidatorTest.php
Labels: major

#2017 Improve typehints
  src/Block/MediaBlockService.php
  src/Controller/Api/GalleryController.php
  src/Controller/Api/MediaController.php
  src/Controller/GalleryController.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataMediaExtension.php
  src/Extra/Pixlr.php
  src/Filesystem/Local.php
  src/Filesystem/Replicate.php
  src/Form/Type/ApiMediaType.php
  src/Generator/GeneratorInterface.php
  src/Generator/IdGenerator.php
  src/Generator/PathGenerator.php
  src/Generator/UuidGenerator.php
  src/Metadata/AmazonMetadataBuilder.php
  src/Metadata/MetadataBuilderInterface.php
  src/Metadata/NoopMetadataBuilder.php
  src/Metadata/ProxyMetadataBuilder.php
  src/Model/Gallery.php
  src/Model/GalleryInterface.php
  src/Model/GalleryManager.php
  src/Model/Media.php
  src/Model/MediaInterface.php
  src/Model/NoDriverGalleryManager.php
  src/Model/NoDriverMediaManager.php
  src/Security/DownloadStrategyInterface.php
  src/Security/ForbiddenDownloadStrategy.php
  src/Security/PublicDownloadStrategy.php
  src/Security/RolesDownloadStrategy.php
  src/Security/SessionDownloadStrategy.php
  src/Serializer/GallerySerializerHandler.php
  src/Serializer/MediaSerializerHandler.php
  src/Twig/Extension/FormatterMediaExtension.php
  src/Twig/Extension/MediaExtension.php
  src/Twig/GlobalVariables.php
  src/Twig/Node/MediaNode.php
  src/Twig/Node/PathNode.php
  src/Twig/Node/ThumbnailNode.php
  src/Twig/TokenParser/MediaTokenParser.php
  src/Twig/TokenParser/PathTokenParser.php
  src/Twig/TokenParser/ThumbnailTokenParser.php
  src/Validator/Constraints/ValidMediaFormat.php
  tests/App/Entity/Category.php
  tests/DependencyInjection/Compiler/ThumbnailCompilerPassTest.php
  tests/Provider/DailyMotionProviderTest.php
  tests/Provider/FileProviderTest.php
  tests/Provider/ImageProviderTest.php
  tests/Provider/VimeoProviderTest.php
  tests/Provider/YouTubeProviderTest.php
  tests/Resizer/CropResizerTest.php
Labels: major

#2021 Deprecate calling `getContext()` without existing context
  src/Provider/Pool.php
Labels: minor

#2034 Update composer
  composer.json
Labels: major

#2033 Fix more NEXT_MAJOR comments
  src/Admin/GalleryAdmin.php
  src/Form/DataTransformer/ProviderDataTransformer.php
  src/Form/DataTransformer/ServiceProviderDataTransformer.php
  src/Form/Type/ApiMediaType.php
  src/Form/Type/MediaType.php
  src/Resources/config/api_form_doctrine_mongodb.php
  src/Resources/config/api_form_doctrine_orm.php
  src/Resources/config/form.php
  src/Resources/config/gaufrette.php
  src/Resources/translations/SonataMediaBundle.ca.xliff
  src/Resources/translations/SonataMediaBundle.de.xliff
  src/Resources/translations/SonataMediaBundle.en.xliff
  src/Resources/translations/SonataMediaBundle.es.xliff
  src/Resources/translations/SonataMediaBundle.fr.xliff
Labels: major

#2072 Inject requestStack instead of SessionInterface to avoid deprecation
  UPGRADE-3.x.md
  src/Resources/config/security.xml
  src/Security/SessionDownloadStrategy.php
  tests/Security/SessionDownloadStrategyTest.php
Labels: minor

#2044 Fix calls to undefined methods from Gaufrette
  UPGRADE-3.x.md
  src/Filesystem/Replicate.php
Labels: minor

#2076 Fix pixlr not able to handle nullable extension
  src/Extra/Pixlr.php
Labels: patch

#2075 Flip choices options
  src/Block/FeatureMediaBlockService.php
  src/Block/GalleryListBlockService.php
Labels: patch

#2077 Deprecate unused argument 3 in `Replicate::write()`
  UPGRADE-3.x.md
  src/Filesystem/Replicate.php
Labels: minor

#2081 Bump PHPStan level to 1
  phpstan.neon.dist
  src/Admin/ORM/MediaAdmin.php
  tests/Block/GalleryListBlockServiceTest.php
Labels: pedantic

#2083 Fix support for "kriswallsmith/buzz" <0.16
  src/Client/BuzzClient.php
Labels: minor
