Repository sonata-project/SonataMediaBundle, pull requests merged in 2021-11, with the labels that each got.

#2193 Remove dependency with doctrine/dbal
  composer.json
  src/Model/NoDriverGalleryManager.php
  src/Model/NoDriverMediaManager.php
Labels: pedantic

#2195 Update phpstan to 1.0
  composer.json
  phpstan.neon.dist
  src/DependencyInjection/Compiler/AddProviderCompilerPass.php
  src/DependencyInjection/Configuration.php
  src/Form/DataTransformer/ProviderDataTransformer.php
  src/Provider/FileProvider.php
  src/Provider/ImageProvider.php
  tests/App/Entity/Context.php
  tests/DependencyInjection/Compiler/ThumbnailCompilerPassTest.php
  tests/Form/DataTransformer/ProviderDataTransformerTest.php
  tests/Form/Type/AbstractTypeTest.php
  tests/Provider/FileProviderTest.php
Labels: pedantic

#2196 Make phpstan more strict
  phpstan.neon.dist
  src/Document/BaseGallery.php
  src/Document/BaseMedia.php
  src/Entity/BaseGallery.php
  src/Entity/BaseMedia.php
  src/Model/Gallery.php
  src/Model/Media.php
  tests/Form/Type/AbstractTypeTest.php
  tests/Provider/AbstractProviderTest.php
Labels: major

#2194 Mark method from abstract classes as final
  UPGRADE-3.x.md
  src/Admin/BaseMediaAdmin.php
  src/Listener/BaseMediaEventSubscriber.php
  src/Model/Gallery.php
  src/Model/Media.php
  src/Provider/BaseProvider.php
  src/Provider/BaseVideoProvider.php
Labels: minor

#2197 Remove conflict against "nelmio/api-doc-bundle" >= 4.0
  UPGRADE-3.x.md
  composer.json
  src/DependencyInjection/SonataMediaExtension.php
  tests/App/AppKernel.php
  tests/Functional/RoutingTest.php
Labels: minor

#2202 Use alpha version of sonata-project/classification-bundle
  composer.json
Labels: pedantic

#2191 Add finals to abstract classes
  src/Model/Gallery.php
  src/Model/GalleryItem.php
  src/Model/Media.php
Labels: major

#2207 Fix: bad annotation ValidMediaFormat constraint
  src/Validator/Constraints/ValidMediaFormat.php
Labels: patch

#2204 Make admin dependency optional for blocks
  src/Block/FeatureMediaBlockService.php
  src/Block/MediaBlockService.php
  src/Resources/config/block.php
  tests/Block/FeatureMediaBlockServiceTest.php
  tests/Block/MediaBlockServiceTest.php
Labels: patch

#2177 Add support for "jms/serializer-bundle" 4.x
  composer.json
Labels: minor, dependencies

#2214 Fix block service registration
  src/Resources/config/block.php
Labels: bug

#2211 Improve error message when uploading image without correct extension or mimetype
  src/Provider/ImageProvider.php
  src/Thumbnail/FormatThumbnail.php
  tests/Fixtures/logo-png-without-ext
  tests/Provider/ImageProviderTest.php
Labels: patch

#2219 Make admin dependency optional for blocks
  src/Block/GalleryBlockService.php
  src/Resources/config/block.php
  tests/Block/GalleryBlockServiceTest.php
Labels: bug

#2221 Fix tests
  composer.json
  tests/App/Entity/Context.php
Labels: pedantic

#2230 Update advanced_configuration.rst
  docs/reference/advanced_configuration.rst
Labels: docs
