Repository sonata-project/SonataMediaBundle, pull requests merged in 2022-01, with the labels that each got.

#2256 Use stable version of classification-bundle
  composer.json
  src/Admin/BaseMediaAdmin.php
  src/Admin/GalleryAdmin.php
  src/Admin/ORM/MediaAdmin.php
  src/Controller/MediaAdminController.php
Labels: major

#2264 Avoid using final for getters/setters
  psalm-baseline.xml
  psalm.xml
  src/Model/Gallery.php
  src/Model/GalleryItem.php
  src/Model/Media.php
  src/Provider/BaseVideoProvider.php
Labels: critical, patch

#2266 Fix file thumbnail generation
  src/DependencyInjection/Configuration.php
Labels: patch

#2263 Improve functional tests
  composer.json
  phpunit.xml.dist
  tests/App/AppKernel.php
  tests/App/Resources/config/services.php
  tests/Functional/Admin/GalleryAdminTest.php
  tests/Functional/Admin/GalleryItemAdminTest.php
  tests/Functional/Admin/MediaAdminTest.php
Labels: pedantic

#2269 Add dama/doctrine-test-bundle
  composer.json
  phpunit.xml.dist
Labels: pedantic

#2267 Use jsonb to avoid problems on batch delete
  UPGRADE-4.0.md
  src/Resources/config/doctrine/BaseMedia.orm.xml
Labels: major

#2270 Prepare 4.0.0 release
  CHANGELOG.md
Labels: major
