Repository sonata-project/SonataMediaBundle, pull requests merged in 2022-06, with the labels that each got.

#2310 Bump imagine library
  composer.json
Labels: minor

#2313 Allow reusing of the MediaType for other correctly interfaced media objects
  src/Form/Type/MediaType.php
Labels: minor

#2314 Fix deprecations for commands while maintian lazyness
  composer.json
  src/Command/AddMassMediaCommand.php
  src/Command/AddMediaCommand.php
  src/Command/CleanMediaCommand.php
  src/Command/FixMediaContextCommand.php
  src/Command/RefreshMetadataCommand.php
  src/Command/RemoveThumbsCommand.php
  src/Command/SyncThumbsCommand.php
  src/Command/UpdateCdnStatusCommand.php
  tests/App/AppKernel.php
  tests/App/Resources/config/config.yaml
  tests/App/Resources/config/config_sonata_block_v4.yaml
Labels: patch

#2316 Fix next major comment
  src/Command/AddMassMediaCommand.php
  src/Command/AddMediaCommand.php
  src/Command/CleanMediaCommand.php
  src/Command/FixMediaContextCommand.php
  src/Command/RefreshMetadataCommand.php
  src/Command/RemoveThumbsCommand.php
  src/Command/SyncThumbsCommand.php
  src/Command/UpdateCdnStatusCommand.php
Labels: pedantic

#2318 Add rector
  .gitattributes
  .github/workflows/qa.yaml
  Makefile
  composer.json
  rector.php
  src/Admin/BaseMediaAdmin.php
  src/Admin/GalleryAdmin.php
  src/Admin/GalleryItemAdmin.php
  src/CDN/CloudFrontVersion3.php
  src/Command/AddMassMediaCommand.php
  src/Controller/GalleryAdminController.php
  src/Controller/MediaAdminController.php
  src/DependencyInjection/SonataMediaExtension.php
  src/Document/GalleryManager.php
  src/Document/MediaManager.php
  src/Entity/GalleryManager.php
  src/Entity/MediaManager.php
  src/Exception/NoDriverException.php
  src/Form/Type/MediaType.php
  src/Model/Gallery.php
  src/Model/GalleryManagerInterface.php
  src/Model/MediaManagerInterface.php
  src/Provider/BaseVideoProvider.php
  src/Provider/ImageProvider.php
  src/Provider/Metadata.php
  src/Resizer/CropResizer.php
  src/Resizer/ResizerInterface.php
  src/Resizer/SquareResizer.php
  tests/App/Entity/Gallery.php
  tests/Block/GalleryBlockServiceTest.php
  tests/Controller/GalleryAdminControllerTest.php
  tests/Fixtures/FilesystemTestCase.php
  tests/Functional/Admin/GalleryAdminTest.php
  tests/Functional/Admin/GalleryItemAdminTest.php
  tests/Functional/Admin/MediaAdminTest.php
  tests/Functional/Command/AddMediaCommandTest.php
  tests/Generator/IdGeneratorTest.php
  tests/Messenger/GenerateThumbnailsHandlerTest.php
  tests/Metadata/AmazonMetadataBuilderTest.php
  tests/Provider/BaseProviderTest.php
  tests/Provider/DailyMotionProviderTest.php
  tests/Provider/FileProviderTest.php
  tests/Provider/ImageProviderTest.php
  tests/Provider/VimeoProviderTest.php
  tests/Provider/YouTubeProviderTest.php
  tests/Resizer/CropResizerTest.php
  tests/Resizer/SimpleResizerTest.php
  tests/Resizer/SquareResizerTest.php
  tests/Security/RolesDownloadStrategyTest.php
  tests/Thumbnail/LiipImagineThumbnailTest.php
  tests/Thumbnail/MessengerThumbnailTest.php
  tests/Twig/MediaRuntimeTest.php
Labels: pedantic

#2317 Allow persistence ^3
  composer.json
Labels: minor
