Repository sonata-project/SonataMediaBundle, pull requests merged in 2022-02, with the labels that each got.

#2273 Fix gallery translations
  src/Admin/GalleryAdmin.php
  src/Resources/translations/SonataMediaBundle.bg.xliff
  src/Resources/translations/SonataMediaBundle.ca.xliff
  src/Resources/translations/SonataMediaBundle.cs.xliff
  src/Resources/translations/SonataMediaBundle.de.xliff
  src/Resources/translations/SonataMediaBundle.en.xliff
  src/Resources/translations/SonataMediaBundle.es.xliff
  src/Resources/translations/SonataMediaBundle.fa.xliff
  src/Resources/translations/SonataMediaBundle.fi.xliff
  src/Resources/translations/SonataMediaBundle.fr.xliff
  src/Resources/translations/SonataMediaBundle.hu.xliff
  src/Resources/translations/SonataMediaBundle.it.xliff
  src/Resources/translations/SonataMediaBundle.ja.xliff
  src/Resources/translations/SonataMediaBundle.lt.xliff
  src/Resources/translations/SonataMediaBundle.nl.xliff
  src/Resources/translations/SonataMediaBundle.pl.xliff
  src/Resources/translations/SonataMediaBundle.pt_BR.xliff
  src/Resources/translations/SonataMediaBundle.ro.xliff
  src/Resources/translations/SonataMediaBundle.ru.xliff
  src/Resources/translations/SonataMediaBundle.sl.xliff
  src/Resources/translations/SonataMediaBundle.uk.xliff
Labels: patch, bug

#2275 Allow psr/log 3 and translation-contracts 3
  composer.json
Labels: minor

#2271 Backport ImageProviderInterface from 4.x
  src/Provider/ImageProvider.php
  src/Provider/ImageProviderInterface.php
  src/Validator/Constraints/ImageUploadDimensionValidator.php
  tests/Fixtures/SonataClassificationBundle/Validator/Constraints/ImageUploadDimensionValidatorTest.php
Labels: minor

#2280 Fix root category check
  src/Listener/ORM/MediaEventSubscriber.php
  tests/Listener/ORM/MediaEventSubscriberTest.php
Labels: patch

#2285 Detect extension if no one is provided
  src/Provider/ImageProvider.php
  tests/Provider/ImageProviderTest.php
  tests/bootstrap.php
Labels: patch

#2289 Avoid adminBundle deprecations
  composer.json
  src/Admin/BaseMediaAdmin.php
  src/Admin/GalleryAdmin.php
  src/Resources/config/doctrine_mongodb_admin.php
  src/Resources/config/doctrine_orm_admin.php
  tests/Admin/BaseMediaAdminTest.php
  tests/Admin/GalleryAdminTest.php
  tests/Admin/GalleryItemAdminTest.php
  tests/Admin/ORM/MediaAdminTest.php
  tests/Provider/AbstractProviderTest.php
Labels: patch
