Repository sonata-project/SonataMediaBundle, pull requests merged in 2023-04, with the labels that each got.

#2377 Fix MongoDB Mapping
  src/Resources/config/doctrine/BaseGallery.mongodb.xml
  src/Resources/config/doctrine/BaseGalleryItem.mongodb.xml
  src/Resources/config/doctrine/BaseMedia.mongodb.xml
Labels: pedantic

#2379 Fix ORM xmlns
  src/Resources/config/doctrine/BaseGallery.orm.xml
  src/Resources/config/doctrine/BaseGalleryItem.orm.xml
  src/Resources/config/doctrine/BaseMedia.orm.xml
Labels: patch

#2384 Fix AmazonMetadataBuilder definition
  src/DependencyInjection/SonataMediaExtension.php
  src/Resources/config/gaufrette.php
Labels: patch

#2386 DevKit updates for 4.x branch
  .github/workflows/auto-merge-dev-kit.yaml
  README.md
Labels: automerge
