Repository sonata-project/SonataMediaBundle, pull requests merged in 2023-06, with the labels that each got.

#2396 Add support for BlockBundle 5.0
  .github/workflows/test.yaml
  composer.json
  tests/Block/FeatureMediaBlockServiceTest.php
  tests/Block/GalleryBlockServiceTest.php
  tests/Block/MediaBlockServiceTest.php
Labels: minor

#2397 Release 4.10.0
  CHANGELOG.md
Labels: dev-kit

#2398 Update rector
  composer.json
Labels: pedantic
