Repository sonata-project/SonataMediaBundle, pull requests merged in 2023-05, with the labels that each got.

#2387 DevKit updates for 4.x branch
  .github/workflows/lint.yaml
  .github/workflows/qa.yaml
  .github/workflows/symfony-lint.yaml
  .github/workflows/test.yaml
Labels: automerge, dev-kit

#2390 Up rector to 0.16
  composer.json
Labels: pedantic

#2391 DevKit updates for 4.x branch
  .github/workflows/test.yaml
  tests/Provider/FileProviderTest.php
Labels: automerge, dev-kit

#2393 Add support for form-extensions 2.0
  composer.json
Labels: minor

#2394 Release 4.9.0
  CHANGELOG.md
Labels: dev-kit
