Repository sonata-project/SonataMediaBundle, pull requests merged in 2023-07, with the labels that each got.

#2405 Fix: SimpleResizer calculation in round() can return invalid value for image resizing. (4.x)
  src/Resizer/SimpleResizer.php
  tests/Resizer/SimpleResizerTest.php
Labels: patch

#2403 DevKit updates for 4.x branch
  .github/workflows/test.yaml
Labels: automerge, dev-kit

#2406 Solve static analysis errors
  src/Block/FeatureMediaBlockService.php
  src/Block/GalleryBlockService.php
  src/Block/GalleryListBlockService.php
  src/Block/MediaBlockService.php
  tests/App/AppKernel.php
  tests/Block/FeatureMediaBlockServiceTest.php
  tests/Block/GalleryBlockServiceTest.php
  tests/Block/MediaBlockServiceTest.php
  tests/Provider/FileProviderTest.php
Labels: pedantic

#2402 Update getMediaBuilder Admin
  src/Block/MediaBlockService.php
Labels: patch
