Repository sonata-project/SonataMediaBundle, pull requests merged in 2023-12, with the labels that each got.

#2427 DevKit updates for 4.x branch
  .github/workflows/test.yaml
  rector.php
Labels: automerge, dev-kit

#2428 DevKit updates for 5.x branch
  rector.php
Labels: automerge, dev-kit

#2430 Allow packages from "symfony/*" ^7
  .github/workflows/test.yaml
  composer.json
  src/Admin/BaseMediaAdmin.php
  src/Admin/GalleryAdmin.php
  src/Controller/GalleryAdminController.php
  src/Controller/MediaAdminController.php
  src/DependencyInjection/Configuration.php
  src/Filesystem/Replicate.php
  src/Form/DataTransformer/ProviderDataTransformer.php
  src/Form/Type/MediaType.php
  src/Messenger/BackwardCompatibleMessageHandlerInterface.php
  src/Messenger/GenerateThumbnailsHandler.php
  src/Provider/Metadata.php
  src/Validator/Constraints/ValidMediaFormat.php
  tests/App/config/config.yaml
Labels: minor, dependencies

#2431 4.11.0
  CHANGELOG.md
Labels: docs

#2433 DevKit updates for 4.x branch
  .php-cs-fixer.dist.php
  src/DependencyInjection/SonataMediaExtension.php
Labels: automerge, dev-kit

#2434 DevKit updates for 5.x branch
  .php-cs-fixer.dist.php
  src/DependencyInjection/SonataMediaExtension.php
Labels: automerge, dev-kit
