Repository sonata-project/SonataMediaBundle, pull requests merged in 2023-03, with the labels that each got.

#2360 Drop older versions an update deps
  composer.json
  psalm.xml
  src/Form/DataTransformer/ProviderDataTransformer.php
  src/Form/Type/MediaType.php
  src/Model/Gallery.php
  src/Resources/config/doctrine/BaseGallery.mongodb.xml
  src/Resources/config/doctrine/BaseGallery.orm.xml
  src/Resources/config/doctrine/BaseGalleryItem.mongodb.xml
  src/Resources/config/doctrine/BaseGalleryItem.orm.xml
  src/Resources/config/doctrine/BaseMedia.mongodb.xml
  src/Resources/config/doctrine/BaseMedia.orm.xml
  src/Validator/Constraints/ValidMediaFormat.php
  tests/App/AppKernel.php
  tests/App/Entity/Category.php
  tests/App/Entity/Context.php
  tests/App/Entity/Gallery.php
  tests/App/Entity/GalleryItem.php
  tests/App/Entity/Media.php
  tests/App/config/config.yaml
  tests/App/config/config_php7.yaml
  tests/App/config/config_php8.yaml
  tests/App/config/config_sonata_block_v4.yaml
  tests/App/config/config_symfony_v4.yaml
  tests/App/config/config_symfony_v5.yaml
  tests/App/config/config_symfony_v6.yaml
  tests/App/config/routes.yaml
  tests/App/config/services.php
  tests/App/templates/truncate_test.html.twig
  tests/Metadata/AmazonMetadataBuilderTest.php
Labels: minor

#2363 Add galley_item translation key for better SonatUserBundle roles display
  src/Resources/translations/SonataMediaBundle.en.xliff
Labels: patch

#2368 Bump DAMA Doctrine Test Bundle
  composer.json
Labels: pedantic

#2371 Use attributes on docs
  docs/reference/installation.rst
  tests/App/Entity/Category.php
  tests/App/Entity/Gallery.php
  tests/App/Entity/GalleryItem.php
  tests/App/Entity/Media.php
Labels: docs

#2372 Change web to public on next major
  src/DependencyInjection/Configuration.php
Labels: pedantic

#2374 Avoid deprecation for boolean on MongoDB ODM
  src/Resources/config/doctrine/BaseGallery.mongodb.xml
  src/Resources/config/doctrine/BaseGalleryItem.mongodb.xml
  src/Resources/config/doctrine/BaseMedia.mongodb.xml
Labels: patch
